Numpy is an fundamental library for scientific computing in python. 
It provides support for arrays and matrices, along with a collection of mathematical functions to operate on these data structures.

In [2]:
!pip install numpy

Defaulting to user installation because normal site-packages is not writeable
  Using cached numpy-2.3.1-cp312-cp312-manylinux_2_28_x86_64.whl.metadata (62 kB)
Using cached numpy-2.3.1-cp312-cp312-manylinux_2_28_x86_64.whl (16.6 MB)


In [6]:
import numpy as np

## create arrays using numpy
## create a 1D array
arr1=np.array([1,2,3,3,4])
print(arr1)
print(type(arr1))
print(arr1.shape)

[1 2 3 3 4]
<class 'numpy.ndarray'>
(5,)


In [ ]:
arr2=np.array([1,3,45,6,5])
arr2.reshape(1,5) ## 1 row and 5 columns
arr2.shape

(5,)

In [ ]:
## 1d
arr3=np.array([[1,2,3,4,5]])
arr3.shape

(1, 5)

In [ ]:
##2d
arr3=np.array([[1,2,3,4,5],[12,3,4,4,3]])
arr3.shape
print(arr3)

[[ 1  2  3  4  5]
 [12  3  4  4  3]]


In [17]:
np.arange(0,10,2).reshape(5,1)

array([[0],
       [2],
       [4],
       [6],
       [8]])

In [18]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [19]:
np.zeros((2,2))

array([[0., 0.],
       [0., 0.]])

In [21]:
## identity matrix
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [22]:
arr = np.array([[1,2,3,4],[5,6,7,8]])
print("Array:\n",arr)
print("Shape:",arr.shape)
print("Dimensions:",arr.ndim)
print("Size of the number of elements:",arr.size)
print("Data type",arr.dtype)
print("Item size(in bytes):",arr.itemsize)

Array:
 [[1 2 3 4]
 [5 6 7 8]]
Shape: (2, 4)
Dimensions: 2
Size of the number of elements: 8
Data type int64
Item size(in bytes): 8


In [ ]:
## numpy vectorized operations
arr1=np.array([1,2,3,4,5])
arr2=np.array([10,20,30,40,50])
## element wise addition
print("Addition:",arr1+arr2)

Addition: [11 22 33 44 55]


In [24]:
## element wise subtraction
print("Subtraction:",arr2-arr1)

Subtraction: [ 9 18 27 36 45]


In [25]:
print("Multiplication:",arr2*arr1)

Multiplication: [ 10  40  90 160 250]


In [26]:
## universal function
arr = np.array([2,3,4,5])
## square root
print(np.sqrt(arr))

[1.41421356 1.73205081 2.         2.23606798]


In [27]:
## exponential
print(np.exp(arr))

[  7.3890561   20.08553692  54.59815003 148.4131591 ]


In [28]:
## sine
np.sin(arr)

array([ 0.90929743,  0.14112001, -0.7568025 , -0.95892427])

In [29]:
np.log(arr)

array([0.69314718, 1.09861229, 1.38629436, 1.60943791])

In [31]:
## array slicing and indexing
arr=np.array([[1,2,3,4,4],[1,2,3,4,5],[2,3,4,4,9]])

In [32]:
print("Array:\n",arr)

Array:
 [[1 2 3 4 4]
 [1 2 3 4 5]
 [2 3 4 4 9]]


In [34]:
print(arr[0][0])

1


In [35]:
arr[2]

array([2, 3, 4, 4, 9])

In [40]:
print(arr[1:,2:])

[[3 4 5]
 [4 4 9]]


In [41]:
arr[:2,1:3]

array([[2, 3],
       [2, 3]])

In [42]:
## modify array elements
arr[0,0]=100
print(arr)

[[100   2   3   4   4]
 [  1   2   3   4   5]
 [  2   3   4   4   9]]


In [43]:
arr[1:]=10
print(arr)

[[100   2   3   4   4]
 [ 10  10  10  10  10]
 [ 10  10  10  10  10]]


In [46]:
## statistical concept--Normalization
## to have a mean of 0 and standard deviation of 1
data = np.array([1,2,3,4,5])
## Calculate the mean and standard deviation
mean = np.mean(data)
std_dev = np.std(data)

## normalized data
normalized_data = (data-mean)/std_dev
print("Normalized data:",normalized_data)


Normalized data: [-1.41421356 -0.70710678  0.          0.70710678  1.41421356]


In [47]:
## mean, median, variance and std deviation
data=[12,34,54,32]
mean=np.mean(data)
print("Mean:",mean)


Mean: 33.0


In [50]:
std_dev=np.std(data)
print("Standard deviation:",std_dev)

Standard deviation: 14.866068747318506


In [51]:
median=np.median(data)
print("Median:",median)

Median: 33.0


In [52]:
variance = np.var(data)

In [53]:
print(variance)

221.0


In [ ]:
## logical operations
data=np.array([2,3,3,4,5,5,6,67,7,7])
data[data>4]

array([ 5,  5,  6, 67,  7,  7])

In [61]:
data=np.array([2,3,3,4,5,5,6,67,7,7])
data[(data>3) & (data<7)]

array([4, 5, 5, 6])